redundant_strings = sorted([
    "STM Cyber is a great cybersecurity company whose slogan is HACK THE UNHACKABLE. They perform their own research and develop their own hacking tools to offer several valuable cybersecurity services like pentesting, Red teams and training.You can check their blog in https://blog.stmcyber.com",
    "STM Cyber also support cybersecurity open source projects like HackTricks :)",
    "RootedCON is the most relevant cybersecurity event in Spain and one of the most important in Europe. With the mission of promoting technical knowledge, this congress is a boiling meeting point for technology and cybersecurity professionals in every discipline.",
    "HackenProofWebSecWebSec is a professional cybersecurity company based in Amsterdam which helps protecting businesses all over the world against the latest cybersecurity threats by providing offensive-security services with a modern approach.",
    "WebSec is an all-in-one security company which means they do it all; Pentesting, Security Audits, Awareness Trainings, Phishing Campagnes, Code Review, Exploit Development, Security Experts Outsourcing and much more.Another cool thing about WebSec is that unlike the industry average WebSec is very confident in their skills, to such an extent that they guarantee the best quality results, it states on their website \"If we can't hack it, You don't pay it!\". For more info take a look at their website and blog!In addition to the above WebSec is also a committed supporter of HackTricks.",
    "DragonJARDragonJAR is a leading offensive cybersecurity company located in Colombia. DragonJAR offers comprehensive offensive cybersecurity services, such as pentesting in various areas and practically any technology, Red Team attack simulations, physical security testing, stress testing, social engineering, source code security review, and cybersecurity training. Additionally, they organize the DragonJAR Security Conference, an international cybersecurity congress that has been held for over a decade, becoming a showcase for the latest security research in Spanish and of great relevance in the region.",
    "DragonJAR es una empresa líder en ciberseguridad ofensiva ubicada en Colombia, DragonJAR ofrece servicios integrales de seguridad informática ofensiva, como pentesting en diversas áreas y prácticamente cualquier tecnología, simulaciones de ataque Red Team, pruebas de seguridad física, pruebas de estrés, ingeniería social, revisión de seguridad en código fuente y capacitación en seguridad informática. Asimismo, organiza la DragonJAR Security Conference, un congreso internacional de seguridad informática que se ha realizado durante más de una década, convirtiéndose en el escaparate para las últimas investigaciones de seguridad en español y de gran relevancia en la región.",
    "LicenseCopyright © Carlos Polop 2023. Except where otherwise specified (the external information copied into the book belongs to the original authors), the text on HACK TRICKS by Carlos Polop is licensed under the Attribution-NonCommercial 4.0 International (CC BY-NC 4.0).",
    "If you want to use it with commercial purposes, contact me.DisclaimerThis book, 'HackTricks,' is intended for educational and informational purposes only. The content within this book is provided on an 'as is' basis, and the authors and publishers make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained within this book. Any reliance you place on such information is therefore strictly at your own risk.The authors and publishers shall in no event be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this book.Furthermore, the techniques and tips described in this book are provided for educational and informational purposes only, and should not be used for any illegal or malicious activities. The authors and publishers do not condone or support any illegal or unethical activities, and any use of the information contained within this book is at the user's own risk and discretion.The user is solely responsible for any actions taken based on the information contained within this book, and should always seek professional advice and assistance when attempting to implement any of the techniques or tips described herein.By using this book, the user agrees to release the authors and publishers from any and all liability and responsibility for any damages, losses, or harm that may result from the use of this book or any of the information contained within it.",
    "Do you work in a cybersecurity company? Do you want to see your company advertised in HackTricks? or do you want to have access to the latest version of the PEASS or download HackTricks in PDF? ",
    "Check the SUBSCRIPTION PLANS!Discover The PEASS Family, our collection of exclusive NFTs",
    "Bug bounty tip: sign up for Intigriti, a premium bug bounty platform created by hackers, for hackers!",
    " Join us at https://go.intigriti.com/hacktricks today, and start earning bounties up to $100,000!\Register - IntigritiRegister - Intigriti",
    " Join us at URL today, and start earning bounties up to $100,000!",
    "HackenProof bounties launch only when their customers deposit the reward budget. You'll get the reward after the bug is verified.",
    "Get experience in web3 pentesting",
    "Blockchain protocols and smart contracts are the new Internet! Master web3 security at its rising days.Become the web3 hacker legend",
    "Corporate SponsorsSTM CyberRootedCONIntigritiTrickestIntruderHACKENPROOFWebSecDragonJARLicenseDisclaimer",
    "Get Access Today:Workflow-powered solution for Bug Bounty, Pentesting, SecOps | TrickestTrickest",
    "Share your hacking tricks by submitting PRs to the hacktricks repo and hacktricks-cloud repo.",
    "Gain reputation points with each verified bug and conquer the top of the weekly leaderboard.",
    "Join the 💬 Discord group or the telegram group or follow me on Twitter 🐦​@carlospolopm.",
    "HackTricksHackTricksTwitterLinkedinSponsorTwitchYoutubeAsk or search…⌃KLinks👾",
    "Intigriti is the Europe's #1 ethical hacking and bug bounty platform.",
    "​☁️ HackTricks Cloud ☁️ -🐦 Twitter 🐦 - 🎙️ Twitch 🎙️ - 🎥 Youtube 🎥",
    "​☁️ HackTricks Cloud ☁️",
    "🐦 Twitter 🐦",
    "🎙️ Twitch 🎙️",
    "🎥 Youtube 🎥",
    "​☁️HackTricks Cloud ☁️",
    "🐦Twitter 🐦",
    "🎙️Twitch 🎙️",
    "🎥Youtube 🎥",
    "Sign up on HackenProof start earning from your hacks!",
    "Platinum SponsorsYour company could be here.",
    "Get the official PEASS & HackTricks swag",
    "Platinum Sponsors",
    "STM Cyber",
    "RootedCON",
    "Intigriti",
    "Corporate Sponsors",
    "HackTricksHacktricks logos & motion design by @ppiernacho.",
    "Join us at today, and start earning bounties up to $100,000!"
    ""
], key=len)[::-1]
cutting_strings = [
    "Next",
    "Previous",
    "References",
]